.\" Manpage for twiner-update.
.\" Contact Mohammed Ismail Ansari <team.terminal@gmail.com> to correct errors or typos.
.TH twiner-update 1 "10/12/2021" "0.1.0"
.SH NAME
twiner \- Configuring and maintaining YOUR Linux made easy
.SH SYNOPSIS
.B twiner-update
.SH DESCRIPTION
Pulls latest updates for twiner from the official repository.
.SH BUGS
No known bugs.
.SH AUTHOR
Mohammed Ismail Ansari (team.terminal@gmail.com)
