.\" Manpage for twiner-start.
.\" Contact Mohammed Ismail Ansari <team.terminal@gmail.com> to correct errors or typos.
.TH twiner-start 1 "10/12/2021" "0.1.0"
.SH NAME
twiner \- Configuring and maintaining YOUR Linux made easy
.SH SYNOPSIS
.B twiner-start
[\fIMODE\fR]
.SH DESCRIPTION
.B twiner
is a collection of bash scripts to help you configure Linux effortlessly from within a command terminal. It provides a set of convenience functions for a growing list of commands, some of which may be used while setting up a freshly installed Linux system while others help save time while performing common tasks without the need to refer to man pages of related commands.
.SH MODES
.TP
.BR <blank> (default)
twiner executes commands on the system as usual.
.TP
.BR debug
twiner executes commands on the system, as well as logs them on the screen.
.TP
.BR simulate
twiner does not execute any command, but only logs them on the screen.
.SH BUGS
No known bugs.
.SH AUTHOR
Mohammed Ismail Ansari (team.terminal@gmail.com)
