#!/usr/bin/env bash

tw_task_fedora_add_additional_software_sources () {
    tw_log "Installing Fusion repos..."
    tw_execute "sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

    tw_log "Updating all packages..."
    tw_execute "sudo dnf update -y"

    tw_log "Fusion repos have been installed!"
}

tw_task_fedora_setup_gui () {
    tw_log "Installing display server..."
    tw_execute "sudo dnf install xorg-x11-server-Xorg xorg-x11-apps xorg-x11-init -y"

    tw_log "Installing graphics driver(s)..."
    tw_menu_title "Please choose your graphics card:"
    tw_menu_option "1" "AMD"
    tw_menu_option "2" "Intel"
    tw_menu_option "3" "Nvidia"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        1)
            graphics_driver="xorg-x11-drv-amdgpu"
            ;;

        2)
            graphics_driver="xorg-x11-drv-intel"
            ;;

        3)
            graphics_driver="xorg-x11-drv-nouveau"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with vesa driver..."
            graphics_driver="xorg-x11-drv-vesa"
            ;;
    esac

    tw_execute "sudo dnf install ${graphics_driver} -y"

    tw_log "Installing a display manager..."
    tw_execute "sudo dnf install sddm -y"

    tw_log "Activating display manager service..."
    tw_execute "sudo systemctl disable display-manager.service"
    tw_execute "sudo systemctl enable sddm"

    tw_log "Installing a desktop environment..."
    tw_task_fedora_install_desktop_environment

    tw_log "Please reboot the system to use the GUI mode"
    tw_confirm "Reboot now?" \
               "sudo reboot 0" \
               "Reboot skipped."
}

tw_task_fedora_install_desktop_environment () {
    tw_error "Not implemented: Installing desktop environment on Fedora!"
}
