#!/usr/bin/env bash

tw_task_fedora_add_additional_software_sources () {
    tw_log "Installing Fusion repos..."
    tw_execute sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    tw_log "Updating all packages..."
    tw_execute sudo dnf update -y

    tw_log "Fusion repos have been installed!"
}

tw_task_fedora_setup_gui () {
    tw_log "Installing display server..."
    tw_execute sudo dnf install xorg-x11-server-Xorg xorg-x11-apps xorg-x11-init -y

    tw_log "Installing graphics driver(s)..."
    tw_menu_title "Please choose your graphics card:"
    tw_menu_option "0" "Vesa/Generic (also suitable for virtual machines)"
    tw_menu_option "a" "AMD"
    tw_menu_option "i" "Intel"
    tw_menu_option "n" "Nvidia"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        a | A)
            graphics_driver="xorg-x11-drv-amdgpu"
            ;;

        i | I)
            graphics_driver="xorg-x11-drv-intel"
            ;;

        n | N)
            graphics_driver="xorg-x11-drv-nouveau"
            ;;

        0 | *)
            tw_log "Proceeding with vesa driver..."
            graphics_driver="xorg-x11-drv-vesa"
            ;;
    esac

    tw_execute sudo dnf install "${graphics_driver}" -y

    tw_log "Installing a display manager..."
    tw_execute sudo dnf install sddm -y

    tw_log "Activating display manager service..."
    tw_execute sudo systemctl disable display-manager.service
    tw_execute sudo systemctl enable sddm

    tw_log "Installing a desktop environment..."
    tw_task_fedora_install_desktop_environment

    tw_log "Please reboot the system to use the GUI mode"
    tw_confirm "Reboot now?" \
               "sudo reboot 0" \
               "Reboot skipped."
}

tw_task_fedora_install_desktop_environment () {
    tw_menu_title "Please select a desktop environment:"
    tw_menu_option "k" "KDE Plasma"
    tw_menu_option "g" "Gnome"
    tw_menu_option "c" "Cinnamon"
    tw_menu_option "b" "Budgie"
    tw_menu_option "m" "MATE"
    tw_menu_option "x" "XFCE"
    tw_menu_option "l" "LXDE"
    tw_menu_option "q" "LXQT"
    tw_menu_option "d" "Deepin"
    tw_menu_option "p" "Pantheon"
    tw_menu_option "e" "Enlightenment"
    tw_menu_option "i" "i3"
    tw_prompt_for_character "" tw_temp

    tw_install_command_action="groupinstall"

    case "${tw_temp}" in
        k | K)
            desktop_environment_packages="KDE Plasma Workspaces"
            ;;

        g | G)
            desktop_environment_packages="GNOME Desktop Environment"
            ;;

        c | C)
            desktop_environment_packages="Cinnamon Desktop"
            ;;

        b | B)
            tw_execute sudo dnf copr enable alunux/budgie-desktop-git -y
            tw_install_command_action="install"
            desktop_environment_packages="budgie-desktop"
            ;;

        m | M)
            desktop_environment_packages="MATE Desktop"
            ;;

        x | X)
            desktop_environment_packages="Xfce Desktop"
            ;;

        l | L)
            desktop_environment_packages="LXDE Desktop"
            ;;

        q | Q)
            tw_install_command_action="install"
            desktop_environment_packages="@lxqt"
            ;;

        d | D)
            desktop_environment_packages="Deepin Desktop"
            ;;

        p | P)
            desktop_environment_packages="pantheon desktop"
            ;;

        e | E)
            tw_install_command_action="install"
            desktop_environment_packages="enlightenment"
            ;;

        i | I)
            tw_install_command_action="install"
            desktop_environment_packages="i3 i3status i3lock"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with KDE plasma..."
            desktop_environment_packages="KDE Plasma Workspaces"
            ;;
    esac

    tw_execute sudo dnf "${tw_install_command_action}" "${desktop_environment_packages}" -y
}
