#!/usr/bin/env bash

# Set root directory
if [ $(command -v realpath) ]; then
    tw_root_dir="$(readlink -f "${BASH_SOURCE[0]}" | xargs realpath | xargs dirname)"
else
    tw_root_dir=$(cd "$(dirname $BASH_SOURCE[0])" ; pwd -P)
fi

# Load resources
. "${tw_root_dir}/lib"
. "${tw_root_dir}/tasks/all"

# Set mode from argument
tw_mode="${1}"

# Determine platform
tw_determine_platform
