#!/usr/bin/env bash

# Set root directory
tw_root_dir="$(readlink -f "${BASH_SOURCE[0]}" | xargs realpath | xargs dirname)"

# Load resources
. "${tw_root_dir}/lib"
. "${tw_root_dir}/tasks/all"

# Set mode from argument
tw_mode="${1}"

# Determine platform
tw_determine_platform
