#!/usr/bin/env bash

# Set root directory
tw_root_dir=$(dirname "${0}")

. "${tw_root_dir}/lib"
. "${tw_root_dir}/tasks"
. "${tw_root_dir}/distros/debian"
. "${tw_root_dir}/distros/fedora"
. "${tw_root_dir}/distros/arch"

tw_mode="${1}"

clear

while true
do
    tw_menu_title "Please select a task to perform:"
    tw_menu_option "1" "Set hostname"
    tw_menu_option "2" "Create users"
    tw_menu_option "3" "Change user shell"
    tw_menu_option "4" "Generate SSH key"
    tw_menu_option "5" "Add additional software sources"
    tw_menu_option "6" "Setup GUI"
    tw_menu_option "7" "Install desktop environment"
    tw_menu_option "q" "Quit"

    tw_prompt_for_character "Make a selection..." tw_temp
    clear

    case "${tw_temp}" in
        1)
            tw_task_set_hostname
            ;;

        2)
            tw_task_create_users
            ;;

        3)
            tw_task_change_user_shell
            ;;

        4)
            tw_task_generate_ssh_key
            ;;

        5)
            tw_task_add_additional_software_sources
            ;;

        6)
            tw_task_setup_gui
            ;;

        7)
            tw_task_install_desktop_environment
            ;;

        q | Q)
            clear
            exit 0
            ;;

        *)
            tw_error "Invalid selection!"
            ;;
    esac

    tw_pause "Press any key to continue..."
    clear
done
