#!/usr/bin/env bash

tw_task_set_hostname () {
    tw_log "Current hostname is '${HOSTNAME}'"

    tw_prompt "Enter a new hostname:" tw_temp
    tw_execute "hostnamectl set-hostname ${tw_temp}"

    tw_handle_last_command_status "${?}" \
                                  "Hostname set to '${tw_temp}'" \
                                  "Hostname could not be set!"
}

tw_task_create_users () {
    local tw_temp_useradd_command="sudo useradd"

    tw_prompt "Enter a username:" tw_temp_username
    tw_temp_useradd_command="${tw_temp_useradd_command} ${tw_temp_username} -m -g users"

    tw_prompt "Enter the full name of the user:" tw_temp
    tw_temp_useradd_command="${tw_temp_useradd_command} -c ${tw_temp}"

    cat /etc/shells
    tw_prompt "Select the default shell for the user (choose an option from the list or leave blank to use the default):" tw_temp
    if [ "${tw_temp}" ]; then
        tw_temp_useradd_command="${tw_temp_useradd_command} -s ${tw_temp}"
    fi

    tw_execute "${tw_temp_useradd_command}"

    tw_handle_last_command_status "${?}" \
                                  "User '${tw_temp_username}' successfully created!" \
                                  "User could not be created!"

    tw_execute "sudo passwd ${tw_temp_username}"
}

tw_task_change_user_shell () {
    local tw_temp_chsh_command="chsh"

    tw_prompt "Enter the username to change the shell for (default: ${USER}):" tw_temp_username

    tw_log "Current active shell is '${SHELL}'"

    cat /etc/shells
    tw_prompt "Select a shell from the above list:" tw_temp
    tw_temp_chsh_command="${tw_temp_chsh_command} -s ${tw_temp}"

    if [ "${tw_temp_username}" ]; then
        tw_temp_chsh_command="${tw_temp_chsh_command} ${tw_temp_username}"
    fi

    tw_execute "${tw_temp_chsh_command}"

    tw_handle_last_command_status "${?}" \
                                  "Shell changed to '${tw_temp}', you may need to re-login to see the changes." \
                                  "Shell could not be changed!"
}

tw_task_generate_ssh_key () {
    tw_prompt "Enter a comment (could be your email address) for the key:" tw_temp

    tw_execute "ssh-keygen -t rsa -b 4096 -C ${tw_temp}"
}

tw_task_add_additional_software_sources () {
    tw_execute_based_on_platform tw_task_debian_add_additional_software_sources \
                                 tw_task_fedora_add_additional_software_sources \
                                 tw_task_arch_add_additional_software_sources
}

tw_task_setup_gui () {
    tw_execute_based_on_platform tw_task_debian_setup_gui \
                                 tw_task_fedora_setup_gui \
                                 tw_task_arch_setup_gui
}

tw_task_install_desktop_environment () {
    tw_execute_based_on_platform tw_task_debian_install_desktop_environment \
                                 tw_task_fedora_install_desktop_environment \
                                 tw_task_arch_install_desktop_environment
}
