#!/usr/bin/env bash

# Load resources
. "$(readlink -f "${BASH_SOURCE[0]}" | xargs realpath | xargs dirname)/load"

tw_log "Pulling updates from git..."
git pull origin master
tw_log "twiner is now up-to-date!"

