#!/usr/bin/env bash

# Capture parent directories
if [ $(command -v realpath) ]; then
    root_directory=$(readlink -f "${BASH_SOURCE[0]}" | xargs realpath | xargs dirname)
else
    root_directory=$(cd "$(dirname $BASH_SOURCE[0])" ; pwd -P)
fi

# Load resources
. "${root_directory}/load"

tw_log "Pulling updates from git..."
git -C "${root_directory}" pull origin master
tw_log "twiner is now up-to-date!"

