#!/usr/bin/env bash

# Function to add additional software repos in Arch
tw_task_arch_add_additional_software_sources () {
    tw_log "Install Archlinux keyring..."
    tw_execute sudo pacman -S archlinux-keyring --noconfirm

    tw_log "Updating all packages..."
    tw_execute sudo pacman -Syu --noconfirm

    tw_log "Installing git..."
    tw_execute sudo pacman -S git --noconfirm

    tw_log "Installing yay for AUR packages..."
    tw_execute mkdir temp
    tw_execute git clone https://aur.archlinux.org/yay.git ./temp/yay
    tw_execute cd ./temp/yay
    tw_execute makepkg -si --noconfirm
    tw_execute cd ../../
    tw_execute rm -rf ./temp

    tw_log "You may now use 'yay' to install packages from AUR"
}

# Function to setup GUI from a CUI environment in Arch
tw_task_arch_setup_gui () {
    tw_log "Installing display server..."
    tw_task_arch_install_display_server

    tw_log "Installing graphics driver(s)..."
    tw_task_arch_install_graphic_drivers

    tw_log "Installing a display manager..."
    tw_confirm "Install a display manager and set graphical mode on startup?" \
               tw_task_arch_install_display_manager \
               "Display manager not installed, please use ~/.xinitrc to start graphical mode on demand."

    tw_log "Installing a desktop environment..."
    tw_task_arch_install_desktop_environment
}

# Function to install a display server in Arch
tw_task_arch_install_display_server () {
    tw_execute sudo pacman -S xorg-server xorg-apps xorg-xinit --noconfirm
}

# Function to install graphic drivers in Arch
tw_task_arch_install_graphic_drivers () {
    tw_menu_title "Please choose your graphics card:"
    tw_menu_option "0" "Vesa/Generic (also suitable for virtual machines)"
    tw_menu_option "a" "AMD"
    tw_menu_option "i" "Intel"
    tw_menu_option "n" "Nvidia"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        a | A)
            graphics_driver="xf86-video-amdgpu"
            ;;

        i | I)
            graphics_driver="xf86-video-intel"
            ;;

        n | N)
            graphics_driver="xf86-video-nouveau"
            ;;

        0 | *)
            tw_log "Proceeding with vesa driver..."
            graphics_driver="xf86-video-vesa"
            ;;
    esac

    tw_execute sudo pacman -S "${graphics_driver}" --noconfirm
}

# Function to install a display manager in Arch
tw_task_arch_install_display_manager () {
    tw_menu_title "Please select a display manager:"
    tw_menu_option "g" "GNOME Display Manager (GDM)"
    tw_menu_option "s" "Simple Desktop Display Manager (SDDM)"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        g | G)
            dm_package_name="gdm"
            dm_service_name="gdm"
            ;;

        s | S)
            dm_package_name="sddm"
            dm_service_name="sddm"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with GDM..."
            dm_package_name="gdm"
            dm_service_name="gdm"
            ;;
    esac

    tw_execute sudo pacman -S ${dm_package_name} --noconfirm
    tw_execute sudo systemctl disable display-manager.service
    tw_execute sudo systemctl enable ${dm_service_name}
}

# Function to install a desktop environment in Arch
tw_task_arch_install_desktop_environment () {
    tw_menu_title "Please select a desktop environment:"
    tw_menu_option "k" "KDE Plasma"
    tw_menu_option "g" "Gnome"
    tw_menu_option "c" "Cinnamon"
    tw_menu_option "b" "Budgie"
    tw_menu_option "m" "MATE"
    tw_menu_option "x" "XFCE"
    tw_menu_option "l" "LXDE"
    tw_menu_option "q" "LXQT"
    tw_menu_option "d" "Deepin"
    tw_menu_option "p" "Pantheon"
    tw_menu_option "e" "Enlightenment"
    tw_menu_option "i" "i3"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        k | K)
            desktop_environment_packages="plasma kde-applications"
            ;;

        g | G)
            desktop_environment_packages="gnome gnome-extra"
            ;;

        c | C)
            desktop_environment_packages="cinnamon"
            ;;

        b | B)
            desktop_environment_packages="budgie-desktop budgie-extras"
            ;;

        m | M)
            desktop_environment_packages="mate mate-extra"
            ;;

        x | X)
            desktop_environment_packages="xfce4 xfce4-goodies"
            ;;

        l | L)
            desktop_environment_packages="lxde"
            ;;

        q | Q)
            desktop_environment_packages="lxqt"
            ;;

        d | D)
            desktop_environment_packages="deepin deepin-extra"
            ;;

        p | P)
            desktop_environment_packages="pantheon"
            ;;

        e | E)
            desktop_environment_packages="enlightenment"
            ;;

        i | I)
            desktop_environment_packages="i3 dmenu"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with KDE plasma..."
            desktop_environment_packages="plasma kde-applications"
            ;;
    esac

    tw_execute sudo pacman -S ${desktop_environment_packages} --noconfirm
}
