#!/usr/bin/env bash

# Function to add additional software repos in Debian
tw_task_debian_add_additional_software_sources () {
    tw_log "Updating and upgrading system..."
    tw_execute sudo apt update -y
    tw_execute sudo apt upgrade -y

    tw_log "System is now updated!"
}

# Function to setup GUI from a CUI environment in Debian
tw_task_debian_setup_gui () {
    tw_log "Installing display server..."
    tw_execute sudo apt install xorg -y

    tw_log "Installing graphics driver(s)..."
    tw_menu_title "Please choose your graphics card:"
    tw_menu_option "0" "Vesa/Generic (also suitable for virtual machines)"
    tw_menu_option "a" "AMD"
    tw_menu_option "i" "Intel"
    tw_menu_option "n" "Nvidia"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        a | A)
            graphics_driver="xserver-xorg-video-amdgpu"
            ;;

        i | I)
            graphics_driver="xserver-xorg-video-intel"
            ;;

        n | N)
            graphics_driver="xserver-xorg-video-nouveau"
            ;;

        0 | *)
            tw_log "Proceeding with vesa driver..."
            graphics_driver="xserver-xorg-video-vesa"
            ;;
    esac

    tw_execute sudo apt install "${graphics_driver}" -y

    tw_log "Installing a display manager..."
    tw_execute sudo apt install sddm -y

    tw_log "Activating display manager service..."
    tw_execute sudo systemctl disable display-manager.service
    tw_execute sudo systemctl enable sddm

    tw_log "Installing a desktop environment..."
    tw_task_debian_install_desktop_environment
}

# # Function to install a desktop environment in Debian
tw_task_debian_install_desktop_environment () {
    tw_menu_title "Please select a desktop environment:"
    tw_menu_option "k" "KDE Plasma"
    tw_menu_option "g" "Gnome"
    tw_menu_option "c" "Cinnamon"
    tw_menu_option "b" "Budgie"
    tw_menu_option "m" "MATE"
    tw_menu_option "x" "XFCE"
    tw_menu_option "l" "LXDE"
    tw_menu_option "q" "LXQT"
    tw_menu_option "d" "Deepin"
    tw_menu_option "p" "Pantheon"
    tw_menu_option "e" "Enlightenment"
    tw_menu_option "i" "i3"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        k | K)
            desktop_environment_packages="kde-plasma-desktop"
            ;;

        g | G)
            desktop_environment_packages="ubuntu-gnome-desktop"
            ;;

        c | C)
            tw_execute sudo add-apt-repository ppa:embrosyn/cinnamon -y
            tw_execute sudo apt update -y
            desktop_environment_packages="cinnamon"
            ;;

        b | B)
            desktop_environment_packages="ubuntu-budgie-desktop"
            ;;

        m | M)
            desktop_environment_packages="ubuntu-mate-desktop"
            ;;

        x | X)
            desktop_environment_packages="xfce4"
            ;;

        l | L)
            desktop_environment_packages="lxde"
            ;;

        q | Q)
            desktop_environment_packages="lxqt"
            ;;

        d | D)
            tw_execute sudo add-apt-repository ppa:leaeasy/dde -y
            tw_execute sudo apt update -y
            desktop_environment_packages="dde dde-file-manager"
            ;;

        p | P)
            tw_execute sudo add-apt-repository ppa:elementary-os/stable -y
            tw_execute sudo apt update -y
            desktop_environment_packages="elementary-desktop"
            ;;

        e | E)
            tw_execute sudo add-apt-repository ppa:niko2040/e19 -y
            tw_execute sudo apt update -y
            desktop_environment_packages="enlightenment terminology"
            ;;

        i | I)
            desktop_environment_packages="i3"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with KDE plasma..."
            desktop_environment_packages="kde-plasma-desktop"
            ;;
    esac

    tw_execute sudo apt install ${desktop_environment_packages} -y
}
