#!/usr/bin/env bash

# Function to add additional software repos in Void
tw_task_void_add_additional_software_sources () {
    tw_log "Adding nonfree and multilib repos..."
    tw_execute sudo xbps-install -Sy void-repo-nonfree void-repo-multilib void-multilib-nonfree
    tw_log "Additional software repos have been added!"

    tw_log "Updating all packages..."
    tw_execute sudo xbps-install -Syu
    tw_log "System is now updated!"

    tw_log "Setting up flatpak..."
    tw_execute sudo xbps-install -Sy flatpak
    tw_execute flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    tw_log "flatpak setup complete!"
}

# Function to setup GUI from a CUI environment in Void
tw_task_void_setup_gui () {
    tw_log "Installing display server..."
    tw_task_void_install_display_server

    tw_log "Installing graphics driver(s)..."
    tw_task_void_install_graphic_drivers

    tw_log "Installing a display manager..."
    tw_confirm "Install a display manager and set graphical mode on startup?" \
               tw_task_void_install_display_manager \
               "Display manager not installed, please use ~/.xinitrc to start graphical mode on demand."

    tw_log "Installing a desktop environment..."
    tw_task_void_install_desktop_environment
}

# Function to install a display server in Void
tw_task_void_install_display_server () {
    tw_execute sudo xbps-install -Sy xorg
}

# Function to install graphic drivers in Void
tw_task_void_install_graphic_drivers () {
   tw_menu_title "Please choose your graphics card:"
    tw_menu_option "0" "Vesa/Generic (also suitable for virtual machines)"
    tw_menu_option "a" "AMD"
    tw_menu_option "i" "Intel"
    tw_menu_option "n" "Nvidia"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        a | A)
            graphics_driver_packages="linux-firmware-amd mesa-dri vulkan-loader mesa-vulkan-radeon amdvlk xf86-video-amdgpu mesa-vaapi mesa-vdpau"
            ;;

        i | I)
            graphics_driver_packages="linux-firmware-intel mesa-dri vulkan-loader mesa-vulkan-intel intel-video-accel"
            ;;

        n | N)
            graphics_driver_packages="xf86-video-nouveau"
            ;;

        0 | *)
            tw_log "Proceeding with vesa driver..."
            graphics_driver_packages="xf86-video-vesa"
            ;;
    esac

    tw_execute sudo xbps-install -Sy ${graphics_driver_packages}
}

# Function to install a display manager in Void
tw_task_void_install_display_manager () {
    # TODO: (entering-the-void) Implement
    tw_error "Not implemented!"
}

# # Function to install a desktop environment in Void
tw_task_void_install_desktop_environment () {
    # TODO: (entering-the-void) Implement
    tw_error "Not implemented!"
}
