#!/usr/bin/env bash

# Function to add additional software repos in Void
tw_task_void_add_additional_software_sources () {
    tw_log "Adding nonfree and multilib repos..."
    tw_execute sudo xbps-install -Sy void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree
    tw_log "Additional software repos have been added!"

    tw_log "Updating all packages..."
    tw_execute sudo xbps-install -Syu
    tw_log "System is now updated!"

    tw_log "Setting up flatpak..."
    tw_execute sudo xbps-install -Sy flatpak
    tw_execute flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    tw_log "flatpak setup complete!"
}

# Function to setup GUI from a CUI environment in Void
tw_task_void_setup_gui () {
    tw_log "Installing display server..."
    tw_task_void_install_display_server

    tw_log "Installing graphics driver(s)..."
    tw_task_void_install_graphic_drivers

    tw_log "Installing a display manager..."
    tw_confirm "Install a display manager and set graphical mode on startup?" \
               tw_task_void_install_display_manager \
               "Display manager not installed, please use ~/.xinitrc to start graphical mode on demand."

    tw_log "Installing a desktop environment..."
    tw_task_void_install_desktop_environment
}

# Function to install a display server in Void
tw_task_void_install_display_server () {
    tw_execute sudo xbps-install -Sy xorg
}

# Function to install graphic drivers in Void
tw_task_void_install_graphic_drivers () {
   tw_menu_title "Please choose your graphics card:"
    tw_menu_option "0" "Vesa/Generic (also suitable for virtual machines)"
    tw_menu_option "a" "AMD"
    tw_menu_option "i" "Intel"
    tw_menu_option "n" "Nvidia"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        a | A)
            graphics_driver_packages="linux-firmware-amd mesa-dri vulkan-loader mesa-vulkan-radeon amdvlk xf86-video-amdgpu mesa-vaapi mesa-vdpau"
            ;;

        i | I)
            graphics_driver_packages="linux-firmware-intel mesa-dri vulkan-loader mesa-vulkan-intel intel-video-accel"
            ;;

        n | N)
            graphics_driver_packages="xf86-video-nouveau"
            ;;

        0 | *)
            tw_log "Proceeding with vesa driver..."
            graphics_driver_packages="xf86-video-vesa"
            ;;
    esac

    tw_execute sudo xbps-install -Sy ${graphics_driver_packages}
}

# Function to install a display manager in Void
tw_task_void_install_display_manager () {
    tw_menu_title "Please select a display manager:"
    tw_menu_option "g" "GNOME Display Manager (GDM)"
    tw_menu_option "s" "Simple Desktop Display Manager (SDDM)"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        g | G)
            dm_package_name="gdm"
            dm_service_name="gdm"
            ;;

        s | S)
            dm_package_name="sddm"
            dm_service_name="sddm"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with GDM..."
            dm_package_name="gdm"
            dm_service_name="gdm"
            ;;
    esac

    tw_execute sudo xbps-install -Sy ${dm_package_name}
    tw_warning "Switching the display manager might affect the current session."
    tw_confirm "Switch display manager services?" \
               tw_task_void_start_display_manager_service \
               "${dm_package_name} service not enabled. Please disable any active display manager services and then run 'ln -s /etc/sv/${dm_service_name} /var/service'."
}

# Function to switch display manager services
tw_task_void_start_display_manager_service() {
    tw_execute sudo rm /var/service/{gdm,sddm}
    tw_execute sudo ln -s /etc/sv/${dm_service_name} /var/service
}

# Function to install a desktop environment in Void
tw_task_void_install_desktop_environment () {
    tw_menu_title "Please select a desktop environment:"
    tw_menu_option "k" "KDE Plasma"
    tw_menu_option "g" "Gnome"
    tw_menu_option "c" "Cinnamon"
    tw_menu_option "b" "Budgie"
    tw_menu_option "m" "MATE"
    tw_menu_option "x" "XFCE"
    tw_menu_option "l" "LXDE"
    tw_menu_option "q" "LXQT"
    tw_menu_option "d" "Deepin"
    tw_menu_option "p" "Pantheon"
    tw_menu_option "e" "Enlightenment"
    tw_menu_option "i" "i3"
    tw_prompt_for_character "" tw_temp

    case "${tw_temp}" in
        k | K)
            desktop_environment_packages="kde5 kde5-baseapps"
            ;;

        g | G)
            desktop_environment_packages="gnome gnome-apps"
            ;;

        c | C)
            desktop_environment_packages="cinnamon"
            ;;

        b | B)
            desktop_environment_packages="budgie-desktop budgie-screensaver"
            ;;

        m | M)
            desktop_environment_packages="mate mate-extra"
            ;;

        x | X)
            desktop_environment_packages="xfce4"
            ;;

        l | L)
            desktop_environment_packages="lxde"
            ;;

        q | Q)
            desktop_environment_packages="lxqt"
            ;;

        d | D)
            # TODO: The package is not available, installation will fail
            desktop_environment_packages="deepin deepin-extra"
            ;;

        p | P)
            # TODO: The package is not available, installation will fail
            desktop_environment_packages="pantheon"
            ;;

        e | E)
            desktop_environment_packages="enlightenment terminology"
            ;;

        i | I)
            desktop_environment_packages="i3 i3lock dmenu"
            ;;

        *)
            tw_log "Invalid option selected, proceeding with KDE plasma..."
            desktop_environment_packages="plasma kde-applications"
            ;;
    esac

    tw_execute sudo xbps-install -Sy ${desktop_environment_packages}
}
